/* -*- C++ -*- */
#ifndef IDL2JNI_GENERATED_MISSIONDATAJC_H
#define IDL2JNI_GENERATED_MISSIONDATAJC_H
#include "MissionDataC.h"
#include "idl2jni_jni.h"
#include "idl2jni_runtime.h"
#include "MissionData_Export.h"
/* Generated by /Users/chidiebereonyedinma/Documents/DDS/OpenDDS-3.13.3/bin/idl2jni running on input file MissionData.idl */


/* Begin MODULE: MissionData */



/* Begin TYPEDEF: PlanData */

MissionData_Export
void copyToCxx (JNIEnv *jni, MissionData::PlanData &target, jobjectArray source);
MissionData_Export
void copyToJava (JNIEnv *jni, jobjectArray &target, const MissionData::PlanData &source, bool createNewObject = false);

/* End TYPEDEF: PlanData */


/* Begin STRUCT: MissionPlan */

MissionData_Export
void copyToCxx (JNIEnv *jni, MissionData::MissionPlan &target, jobject source);
MissionData_Export
void copyToJava (JNIEnv *jni, jobject &target, const MissionData::MissionPlan &source, bool createNewObject = false);

/* End STRUCT: MissionPlan */


/* Begin TYPEDEF: Points */

MissionData_Export
void copyToCxx (JNIEnv *jni, MissionData::Points &target, jobjectArray source);
MissionData_Export
void copyToJava (JNIEnv *jni, jobjectArray &target, const MissionData::Points &source, bool createNewObject = false);

/* End TYPEDEF: Points */


/* Begin STRUCT: NormalizedPoints */

MissionData_Export
void copyToCxx (JNIEnv *jni, MissionData::NormalizedPoints &target, jobject source);
MissionData_Export
void copyToJava (JNIEnv *jni, jobject &target, const MissionData::NormalizedPoints &source, bool createNewObject = false);

/* End STRUCT: NormalizedPoints */


/* Begin TYPEDEF: TelemetryData */

MissionData_Export
void copyToCxx (JNIEnv *jni, MissionData::TelemetryData &target, jobjectArray source);
MissionData_Export
void copyToJava (JNIEnv *jni, jobjectArray &target, const MissionData::TelemetryData &source, bool createNewObject = false);

/* End TYPEDEF: TelemetryData */


/* Begin TYPEDEF: ImageData */

MissionData_Export
void copyToCxx (JNIEnv *jni, MissionData::ImageData &target, jbyteArray source);
MissionData_Export
void copyToJava (JNIEnv *jni, jbyteArray &target, const MissionData::ImageData &source, bool createNewObject = false);

/* End TYPEDEF: ImageData */


/* Begin STRUCT: Telemetry */

MissionData_Export
void copyToCxx (JNIEnv *jni, MissionData::Telemetry &target, jobject source);
MissionData_Export
void copyToJava (JNIEnv *jni, jobject &target, const MissionData::Telemetry &source, bool createNewObject = false);

/* End STRUCT: Telemetry */

/* End MODULE: MissionData */
#endif /* IDL2JNI_GENERATED_MISSIONDATAJC_H */
