// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p16
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_MISSIONDATAC_BL9DJV_H_
#define _TAO_IDL_MISSIONDATAC_BL9DJV_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "MissionData_Export.h"
#include "tao/ORB.h"
#include "tao/Basic_Types.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO MissionData_Export

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace MissionData
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_MISSIONDATA_PLANDATA_CH_)
#define _MISSIONDATA_PLANDATA_CH_

  class PlanData;

  typedef
    ::TAO_VarSeq_Var_T<
        PlanData
      >
    PlanData_var;

  typedef
    ::TAO_Seq_Out_T<
        PlanData
      >
    PlanData_out;

  class MissionData_Export PlanData
    : public
        ::TAO::unbounded_basic_string_sequence<char>
  {
  public:
    PlanData (void);
    PlanData ( ::CORBA::ULong max);
    PlanData (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Char ** buffer,
      ::CORBA::Boolean release = false);
    PlanData (const PlanData &);
    virtual ~PlanData (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef PlanData_var _var_type;
    typedef PlanData_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct MissionPlan;

  typedef
    ::TAO_Var_Var_T<
        MissionPlan
      >
    MissionPlan_var;

  typedef
    ::TAO_Out_T<
        MissionPlan
      >
    MissionPlan_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct MissionData_Export MissionPlan
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef MissionPlan_var _var_type;
    typedef MissionPlan_out _out_type;
    
    ::TAO::String_Manager from;
    ::CORBA::Long planId;
    MissionData::PlanData plan_data;
    MissionData::PlanData obstacles;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_MISSIONDATA_POINTS_CH_)
#define _MISSIONDATA_POINTS_CH_

  class Points;

  typedef
    ::TAO_VarSeq_Var_T<
        Points
      >
    Points_var;

  typedef
    ::TAO_Seq_Out_T<
        Points
      >
    Points_out;

  class MissionData_Export Points
    : public
        ::TAO::unbounded_basic_string_sequence<char>
  {
  public:
    Points (void);
    Points ( ::CORBA::ULong max);
    Points (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Char ** buffer,
      ::CORBA::Boolean release = false);
    Points (const Points &);
    virtual ~Points (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef Points_var _var_type;
    typedef Points_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct NormalizedPoints;

  typedef
    ::TAO_Var_Var_T<
        NormalizedPoints
      >
    NormalizedPoints_var;

  typedef
    ::TAO_Out_T<
        NormalizedPoints
      >
    NormalizedPoints_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct MissionData_Export NormalizedPoints
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef NormalizedPoints_var _var_type;
    typedef NormalizedPoints_out _out_type;
    
    ::TAO::String_Manager from;
    ::CORBA::Long pointsId;
    MissionData::Points points_data;
  };

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_MISSIONDATA_TELEMETRYDATA_CH_)
#define _MISSIONDATA_TELEMETRYDATA_CH_

  class TelemetryData;

  typedef
    ::TAO_VarSeq_Var_T<
        TelemetryData
      >
    TelemetryData_var;

  typedef
    ::TAO_Seq_Out_T<
        TelemetryData
      >
    TelemetryData_out;

  class MissionData_Export TelemetryData
    : public
        ::TAO::unbounded_basic_string_sequence<char>
  {
  public:
    TelemetryData (void);
    TelemetryData ( ::CORBA::ULong max);
    TelemetryData (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Char ** buffer,
      ::CORBA::Boolean release = false);
    TelemetryData (const TelemetryData &);
    virtual ~TelemetryData (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef TelemetryData_var _var_type;
    typedef TelemetryData_out _out_type;
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

#if !defined (_MISSIONDATA_IMAGEDATA_CH_)
#define _MISSIONDATA_IMAGEDATA_CH_

  class ImageData;

  typedef
    ::TAO_FixedSeq_Var_T<
        ImageData
      >
    ImageData_var;

  typedef
    ::TAO_Seq_Out_T<
        ImageData
      >
    ImageData_out;

  class MissionData_Export ImageData
    : public
        ::TAO::unbounded_value_sequence<
            ::CORBA::Octet
          >
  {
  public:
    ImageData (void);
    ImageData ( ::CORBA::ULong max);
    ImageData (
      ::CORBA::ULong max,
      ::CORBA::ULong length,
      ::CORBA::Octet* buffer,
      ::CORBA::Boolean release = false);
    ImageData (const ImageData &);
    virtual ~ImageData (void);
    

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef ImageData_var _var_type;
    typedef ImageData_out _out_type;

    

#if (TAO_NO_COPY_OCTET_SEQUENCES == 1)
    ImageData (
        ::CORBA::ULong length,
        const ACE_Message_Block* mb
      )
      : ::TAO::unbounded_value_sequence< ::CORBA::Octet> (length, mb) {}
#endif /* TAO_NO_COPY_OCTET_SEQUENCE == 1 */
  };

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_type.cpp:261

  struct Telemetry;

  typedef
    ::TAO_Var_Var_T<
        Telemetry
      >
    Telemetry_var;

  typedef
    ::TAO_Out_T<
        Telemetry
      >
    Telemetry_out;

  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:51

  struct MissionData_Export Telemetry
  {

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    
    typedef Telemetry_var _var_type;
    typedef Telemetry_out _out_type;
    
    ::TAO::String_Manager from;
    ::CORBA::Long telemetryId;
    MissionData::TelemetryData telemetry_data;
    MissionData::ImageData image;
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module MissionData

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::MissionData::PlanData>
    : public
        Var_Size_Arg_Traits_T<
            ::MissionData::PlanData,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::MissionData::MissionPlan>
    : public
        Var_Size_Arg_Traits_T<
            ::MissionData::MissionPlan,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::MissionData::Points>
    : public
        Var_Size_Arg_Traits_T<
            ::MissionData::Points,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::MissionData::NormalizedPoints>
    : public
        Var_Size_Arg_Traits_T<
            ::MissionData::NormalizedPoints,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::MissionData::TelemetryData>
    : public
        Var_Size_Arg_Traits_T<
            ::MissionData::TelemetryData,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:685

  template<>
  class Arg_Traits< ::MissionData::ImageData>
    : public
        Var_Size_Arg_Traits_T<
            ::MissionData::ImageData,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:947

  template<>
  class Arg_Traits< ::MissionData::Telemetry>
    : public
        Var_Size_Arg_Traits_T<
            ::MissionData::Telemetry,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_MissionData_PlanData_H_
#define _TAO_CDR_OP_MissionData_PlanData_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


MissionData_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const MissionData::PlanData &_tao_sequence);
MissionData_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    MissionData::PlanData &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_MissionData_PlanData_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

MissionData_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const MissionData::MissionPlan &);
MissionData_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, MissionData::MissionPlan &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_MissionData_Points_H_
#define _TAO_CDR_OP_MissionData_Points_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


MissionData_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const MissionData::Points &_tao_sequence);
MissionData_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    MissionData::Points &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_MissionData_Points_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

MissionData_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const MissionData::NormalizedPoints &);
MissionData_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, MissionData::NormalizedPoints &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_MissionData_TelemetryData_H_
#define _TAO_CDR_OP_MissionData_TelemetryData_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


MissionData_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const MissionData::TelemetryData &_tao_sequence);
MissionData_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    MissionData::TelemetryData &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_MissionData_TelemetryData_H_ */

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:68

#if !defined _TAO_CDR_OP_MissionData_ImageData_H_
#define _TAO_CDR_OP_MissionData_ImageData_H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


MissionData_Export ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const MissionData::ImageData &_tao_sequence);
MissionData_Export ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    MissionData::ImageData &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_MissionData_ImageData_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:46


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

MissionData_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const MissionData::Telemetry &);
MissionData_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, MissionData::Telemetry &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "MissionDataC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

